# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9f3b7038d7f46142b551e59d76e5d2f40e58394205ee18fe970ecf4eb245648bb04824c9924cdbbe320b2d875f5f7114942d109df69fe1ce76d1a97c2cd8d122

test:
  secret_key_base: 06193264ac712a8f3a05ed2342de54a581b151f54ce8d369745df441e554cf8bb36a440f78dddc1d3843557bdf794478bedb00d42f5f8cffa2d6ddb2aad5dc41

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
